export interface Country {
    name: string;
    code: string;
  }
  
  export const countries: Country[] = [
      { name: "Nigeria", code: "NG" },
      { name: "England", code: "EG" },
      { name: "Afghanistan", code: "AF" },
      { name: "Albania", code: "AL" },
      { name: "Algeria", code: "DZ" },
      { name: "American Samoa	", code: "AS" },
      { name: "Andorra", code: "AD" },
      { name: "Angola", code: "AO" },
      { name: "Anguilla", code: "AI" },
      { name: "Antarctica", code: "AQ" },
      { name: "Antigua and Barbuda	", code: "AG" },
      { name: "Argentina", code: "AR" },
      { name: "Armenia", code: "AM" },
      { name: "Aruba", code: "AW" },
      { name: "Australia", code: "AU" },
      { name: "Austria", code: "AT" },
      { name: "Azerbaijan", code: "AZ" },
      { name: "Bahamas", code: "BS" },
      { name: "Bahrain", code: "BH" },
      { name: "Bangladesh", code: "BD" },
      { name: "Barbados", code: "BB" },
      { name: "Belarus", code: "BY" },
      { name: "Belgium", code: "BE" },
      { name: "Belize", code: "BZ" },
      { name: "Benin", code: "BJ" },
      { name: "Bermuda", code: "BM" },
      { name: "Bhutan", code: "BT" },
      { name: "Bolivia", code: "BO" },
      { name: "Bonaire, Sint Eustatius and Saba	", code: "BQ" },
      { name: "Bosnia and Herzegovina	", code: "BA" },
      { name: "Botswana", code: "BW" },
      { name: "Bouvet Island	", code: "BV" },
      { name: "Brazil", code: "BR" },
      { name: "Bulgaria", code: "BG" },
      { name: "Burkina Faso	", code: "BF" },
      { name: "Burundi", code: "BI" },
      { name: "Cameroon", code: "CM" },
      { name: "Canada", code: "CA" },
      { name: "Chad", code: "TD" },
      { name: "Chile", code: "CL" },
      { name: "China", code: "CN" },
      { name: "Colombia", code: "CO" },
      { name: "Costa Rica	", code: "CR" },
      { name: "Croatia", code: "HR" },
      { name: "Cuba", code: "CU" },
      { name: "Cyprus", code: "CY" },
      { name: "Côte d'Ivoire	", code: "CI" },
      { name: "Denmark", code: "DK" },
      { name: "Ecuador", code: "EC" },
      { name: "Egypt", code: "EG" },
      { name: "Estonia", code: "EE" },
      { name: "Ethiopia", code: "ET" },
      { name: "Finland", code: "FI" },
      { name: "France", code: "FR" },
      { name: "Gabon", code: "GA" },
      { name: "Gambia", code: "GM" },
      { name: "Georgia", code: "GE" },
      { name: "Germany", code: "DE" },
      { name: "Ghana", code: "GH" },
      { name: "Greece", code: "GR" },
      { name: "Honduras", code: "HN" },
      { name: "Hong Kong	", code: "HK" },
      { name: "Hungary", code: "HU" },
      { name: "Iceland", code: "IS" },
      { name: "India", code: "IN" },
      { name: "Italy", code: "IT" },
      { name: "Jamaica", code: "JM" },
      { name: "Japan", code: "JP" },
      { name: "Kenya", code: "KE" },
      { name: "Korea", code: "KR" },
      { name: "Kuwait", code: "KW" },
      { name: "Madagascar", code: "MG" },
      { name: "Malaysia", code: "MY" },
      { name: "Maldives", code: "MV" },
      { name: "Mexico", code: "MX" },
      { name: "Morocco", code: "MA" },
      { name: "Mozambique", code: "MZ" },
      { name: "Namibia", code: "NA" },
      { name: "Netherlands", code: "NL" },
      { name: "New Zealand	", code: "NZ" },
      { name: "Norway", code: "NO" },
      { name: "Poland", code: "PL" },
      { name: "Portugal", code: "PT" },
      { name: "Qatar", code: "QA" },
      { name: "Romania", code: "RO" },
      { name: "Russia", code: "RU" },
      { name: "Rwanda", code: "RW" },
      { name: "Saint Kitts and Nevis	", code: "KN" },
      { name: "Saudi Arabia	", code: "SA" },
      { name: "Senegal", code: "SN" },
      { name: "Sierra Leone	", code: "SL" },
      { name: "Singapore", code: "SG" },
      { name: "South Africa	", code: "ZA" },
      { name: "Spain", code: "ES" },
      { name: "Sri Lanka	", code: "LK" },
      { name: "Sweden", code: "SE" },
      { name: "Switzerland", code: "CH" },
      { name: "Tanzania", code: "TZ" },
      { name: "Togo", code: "TG" },
      { name: "Tunisia", code: "TN" },
      { name: "Turkey", code: "TR" },
      { name: "Uganda", code: "UG" },
      { name: "Ukraine", code: "UA" },
      { name: "United Arab Emirates", code: "AE" },
      { name: "United States of America", code: "US" },
      { name: "United Kingdom", code: "GB" },
      { name: "Uruguay", code: "UY" },
      { name: "Virgin Islands (British)	", code: "VG" },
      { name: "Virgin Islands (U.S.)	", code: "VI" },
      { name: "Zambia", code: "ZM" },
      { name: "Zimbabwe", code: "ZW" },
    ];